---
title: "IMGS2022 Twitter"
output:
  github_document: default
  html_notebook: default
---

A look at twitter use at the 2022 IMGS conference.

```{r include=FALSE}
library(tidyverse)
library(academictwitteR)

df <- bind_tweets("../../research/testing/", output_format = "tidy")
# remove dupes
df <- df %>% distinct(tweet_id, .keep_all = T)

range(df$created_at)
# mark retweets vs. not
df <- df %>% mutate(is_retweet = ifelse(grepl("RT", text),  1, 0))

```

The top 11 users (since imgs2022 is in there too)

```{r echo=FALSE}
# users and number of tweets
df_users <- df %>% count(user_username) %>% arrange(desc(n))
df_users %>% slice(1:11) %>% rename(`Twitter Username` = user_username, `Number of tweets` = n) %>% knitr::kable()
```

```{r echo=FALSE}
# make a local time tweet
df <- df %>% mutate(local_tw_time = lubridate::with_tz(
  lubridate::ymd_hms(created_at), tzone = "Europe/London"))

df <- df %>% mutate(dow = lubridate::wday(local_tw_time, label = T), day = lubridate::day(local_tw_time))


```
Tweets per day of the conference and by hour of the day

```{r echo=FALSE}
# tweets per day
# tpd <- df  %>% count(day)
# tpd %>% ggplot(aes(day, n)) + geom_col()
# tpd %>% filter(day > 18)%>% ggplot(aes(day, n)) + geom_col()
df %>% 
  filter(day > 17) %>%
  mutate(dow = fct_relevel(dow, "Sat")) %>% 
  ggplot(aes(dow)) + geom_bar(fill = "darkblue") + labs(title = "Tweets by day", subtitle = "#IMGS2022", x = "Conference day", y = "number of tweets") + theme_minimal()

# when do people tweet
twhrs <- df %>% mutate(twhr = lubridate::hour(local_tw_time))
twhrs %>% ggplot(aes(twhr)) + geom_bar(fill = "steelblue") + labs(title = "Tweets by hour of the day", subtitle = "#IMGS2022", x = "Hour of the day", y = "number of tweets") + theme_minimal()
```

What tweets have the most likes, the top 20
```{r echo=FALSE}
# most likes
lks <- df %>% 
  arrange(desc(like_count)) %>% 
  slice(1:20) %>% 
  select(user_username, user_name,text, like_count) %>%
  rename(`Twitter handle` = user_username, `User name` = user_name, `Tweet text` = text, `# of likes` = like_count) %>% 
  knitr::kable()
lks <- gsub("\n\n", "", lks) # since a double line break is messing up the table
lks
```

